logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
spring:
  rabbitmq:
    host: 139.196.16.210
    port: 5672
    virtual-host: forjava
    username: root
    password: root
    connection-timeout: 1s
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-interval: 3 # 最大重试次数
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制，路由失败时返回的错误消息，一般都是由于开发人员自己写错，一般来说不需要开启